BATCH_SIZE: 6
NUM_EPOCHS: 6
MAX_SEQUENCE_LEN: 75
LEARNING_RATE: 0.00014413469371110337
WEIGHT_DECAY: 0.00022233337605920384
EARLY_STOPPING_THRESHOLD: 5

DATASET_NAME: "MultiCoNER2"
# `BC5CDR` or `MultiCoNER2`

FEATURE_EXTRACTOR: "lstm"
# `lstm` or `cnn`

USE_GLOVE: True # `True` or `False`

RMV_STOPWORDS: False # `True` or `False`
LEMMATIZE: False # `True` or `False`

DROPOUT: 0.3736600550686905
INPUT_DIM: 200 
# `50`, `100`, `150` or `300`
N_LAYERS: 4 # number of layers for LSTM OR CNN network
HIDDEN_DIM: 768 # hidden dimension for LSTM OR CNN network

PATH_TO_MODEL_OUTPUT_DIR: "./model_checkpoints/lstm_cnn/"